server:
  port: 8080

spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bankdb
    username: devuser
    password: devpassword
  jpa:
    defer-datasource-initialization: true
  sql.init:
    mode: always
jwt:
  secret: put03lQu3LoL33
  issuer-uri: http://localhost:8080
  
